// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetSettings():Promise<backend.Settings>;

export function GetSettingsPath():Promise<string>;

export function LoadSettings(arg1:string):Promise<void>;

export function OnResize():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SaveFileDialog():Promise<string>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;
