// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateThumbnail(arg1, arg2) {
  return window['go']['backend']['App']['GenerateThumbnail'](arg1, arg2);
}

export function GetMedia(arg1) {
  return window['go']['backend']['App']['GetMedia'](arg1);
}

export function GetMediaByID(arg1) {
  return window['go']['backend']['App']['GetMediaByID'](arg1);
}

export function GetMediaCount(arg1) {
  return window['go']['backend']['App']['GetMediaCount'](arg1);
}

export function GetMediaStats() {
  return window['go']['backend']['App']['GetMediaStats']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetSettingsPath() {
  return window['go']['backend']['App']['GetSettingsPath']();
}

export function IndexDirectory(arg1, arg2) {
  return window['go']['backend']['App']['IndexDirectory'](arg1, arg2);
}

export function IndexSources() {
  return window['go']['backend']['App']['IndexSources']();
}

export function LoadSettings(arg1) {
  return window['go']['backend']['App']['LoadSettings'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['backend']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['backend']['App']['OpenFileDialog']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}
