// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetSettingsPath() {
  return window['go']['backend']['App']['GetSettingsPath']();
}

export function LoadSettings(arg1) {
  return window['go']['backend']['App']['LoadSettings'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['backend']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['backend']['App']['OpenFileDialog']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}
